- menu_name: "Services"

- name: "Product Design"
  url: "/prod-design/"
  title: "Product Design"

- name: "Embedded Software"
  url: "/emb-sw/"
  title: "Embedded Software"

- name: "Technology Stack"
  url: "/tech-stack/"
  title: "Technology Stack"

- name: "Contact Us"
  url: "/contact-us/"
  title: "Contact Us"